<?php

namespace AppBundle\Repository;

/**
 * SousTacheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTacheRepository extends \Doctrine\ORM\EntityRepository
{
}
